# Generated by Django 3.0.8 on 2020-08-07 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10), django.core.validators.int_list_validator]),
        ),
    ]
