# Generated by Django 3.0.8 on 2020-08-07 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_citizen_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='ward_no',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(2)]),
        ),
    ]
