# Generated by Django 3.0.8 on 2020-08-07 06:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_auto_20200807_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_id', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator, django.core.validators.MaxLengthValidator, django.core.validators.int_list_validator])),
                ('ward_no', models.IntegerField(verbose_name=[django.core.validators.MaxLengthValidator(2)])),
                ('tole', models.CharField(max_length=150)),
                ('family_name', models.CharField(max_length=150)),
                ('senior_family_member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profileapp.Citizen')),
            ],
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_animal', models.CharField(max_length=4, validators=[django.core.validators.int_list_validator])),
                ('small_animals', models.CharField(max_length=4, validators=[django.core.validators.int_list_validator])),
                ('bird', models.CharField(max_length=4, validators=[django.core.validators.int_list_validator])),
                ('home_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileapp.Home')),
            ],
        ),
    ]
