# Generated by Django 3.0.8 on 2020-08-07 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_home_livestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='home_id',
            field=models.ForeignKey(blank=True, default=5000, on_delete=django.db.models.deletion.DO_NOTHING, to='profileapp.Home'),
        ),
    ]
