# Generated by Django 3.0.8 on 2020-08-08 04:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_citizen_home_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='home_id',
            new_name='home',
        ),
        migrations.RenameField(
            model_name='livestock',
            old_name='home_id',
            new_name='home',
        ),
        migrations.AddField(
            model_name='citizen',
            name='birth_registration_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='specially_abled',
            field=models.CharField(choices=[('H', 'Hindu'), ('M', 'Muslim'), ('C', 'Christan'), ('B', 'Buddist'), ('S', 'Shikh')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_id',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6), django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='home',
            name='senior_family_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sernior_member', to='profileapp.Citizen'),
        ),
        migrations.AlterField(
            model_name='home',
            name='ward_no',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(2)]),
        ),
        migrations.CreateModel(
            name='FamilyIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=150, verbose_name='source of income')),
                ('amount', models.IntegerField(verbose_name='yearly income')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileapp.Home')),
            ],
        ),
    ]
