# Generated by Django 3.0.8 on 2020-08-08 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0006_auto_20200808_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_id',
            field=models.CharField(max_length=6, validators=[django.core.validators.int_list_validator]),
        ),
    ]
