# Generated by Django 3.0.8 on 2020-08-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0007_auto_20200808_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='ward_no',
            field=models.IntegerField(),
        ),
    ]
