# Generated by Django 3.0.8 on 2020-08-08 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_auto_20200808_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_id',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6), django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='home',
            name='ward_no',
            field=models.CharField(max_length=2, validators=[django.core.validators.int_list_validator]),
        ),
    ]
