# Generated by Django 3.0.8 on 2020-08-08 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0009_auto_20200808_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='ward_no',
        ),
    ]
