# Generated by Django 3.0.8 on 2020-08-13 05:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0011_auto_20200811_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='ward_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='home',
            field=models.ForeignKey(blank=True, default=5000, on_delete=django.db.models.deletion.DO_NOTHING, related_name='house_no', to='profileapp.Home'),
        ),
    ]
