# Generated by Django 3.0.8 on 2020-08-13 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0013_auto_20200813_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='ward_no',
            field=models.CharField(max_length=2, validators=[django.core.validators.int_list_validator]),
        ),
    ]
